### ISSUE TITLE
Allow using pwms stored in configs to generate motifs

### ISSUE THREAD

**Issue by mathysgrapotte** [mathysgrapotte/model-check#5]
User can input motifs in a config file for generating the fasta

**Comment by mathysgrapotte** [comment]
Now that jaspar motifs can be loaded through jaspar, we need to manage that into a config file

**Comment by alessiovignoli** [comment]
can i suggest not to call it config file since4 those are the ones used by the nextflow pipeline?. afterall is just another input file. Which format do we settle on? a txt file with Jasper ID per line of the file? or csv with ids separated by commas possibly on more than one line?.

**Comment by mathysgrapotte** [comment]
CSV could be a better format, maybe I should look into JASPAR when you DL collections of motif ID, what is the format, and yes I don't think we should call it config 👍

**Comment by alessiovignoli** [comment]
Issue #12  is related to this one as well.
